---
- name: "Check if JDK installed: find java executable (1/3)..."
  shell: "su - -c 'which java'"
  ignore_errors: True
  register: _jdk_check_installed
  changed_when: False

- name: "Check if JDK is installed (2/3)..."
  set_fact:
    _jdk_is_installed: "{{ _jdk_check_installed.rc == 0 }}"
  when: _jdk_check_installed is defined
