---
- name: "Set JDK directory's owner and group..."
  file:
    path="{{ _config.jdk_home }}"
    owner="{{ jdk.user.name }}"
    group="{{ jdk.user.group }}"
    state=directory
    recurse=yes
  tags:
    - jdkconfig

- name: 'Set JDK environment variables...'
  template:
    src="../../redhat/templates/java-env.sh"
    dest="{{ jdk.envfile }}"
    mode=0644
  tags:
    - jdkconfig
