---
# file: roles/credentials/tasks/main.yml

- name: "Create login credentials: create group (1/2)..."
  group:
    name="{{ item.groupname }}"
    system="{{ item.is_system }}"
    state=present
  with_items: "{{ credentials.list }}"
  when: item.groupname | match("[a-z_][a-z0-9_]{0,30}")

- name: "Create login credentials: create user (2/2)..."
  user:
    name="{{ item.username }}"
    group="{{ item.groupname }}"
    createhome="{{ item.is_createhome }}"
    system="{{ item.is_system }}"
    state=present
  with_items: "{{ credentials.list }}"
  when: item.username | match("[a-z_][a-z0-9_]{0,30}")
